# Generated by Django 5.2.15 on 2026-07-02 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_type', models.CharField(choices=[('woocommerce', 'WooCommerce'), ('selltico', 'Selltico'), ('tau_commerce', 'TAU Commerce')], max_length=32)),
                ('label', models.CharField(help_text='Human label for this store, e.g. "Prodavnica RS".', max_length=100)),
                ('base_url', models.URLField(help_text='Store base URL. Must use https (http allowed only for localhost/127.0.0.1).')),
                ('key_encrypted', models.TextField()),
                ('secret_encrypted', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_credentials', to='accounts.organization')),
            ],
            options={
                'unique_together': {('organization', 'label')},
            },
        ),
    ]
