# Generated by Django 5.2.15 on 2026-07-02 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import batches.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_file', models.FileField(upload_to=batches.models.batch_upload_path)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('source_script', models.CharField(choices=[('latinica', 'Latinica'), ('cirilica', 'Ćirilica')], default='latinica', max_length=20)),
                ('provider', models.CharField(choices=[('fake', 'Fake'), ('anthropic', 'Anthropic')], default='fake', max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('total_count', models.IntegerField(default=0)),
                ('needs_review_count', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('generate', 'Generate'), ('approve', 'Approve'), ('reject', 'Reject'), ('publish', 'Publish'), ('publish_failed', 'Publish failed')], max_length=20)),
                ('product_id', models.CharField(blank=True, max_length=200)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.organization')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='batches.batch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=200)),
                ('cirilica', models.TextField()),
                ('latinica', models.TextField()),
                ('needs_review', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], db_index=True, default='pending', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('publish_error', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='batches.batch')),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['product_id'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'product_id'), name='unique_batch_product_id')],
            },
        ),
    ]
